import streamlit as st
st.set_page_config(page_title="Home page")
st.title("Low Li Wen's e-portfolio")
st.write("Lets look at the different options in my e-portfolio")
st.page_link("home.py",label="Home",icon="🏠")
st.page_link("pages/about me.py",label="About me :D",icon="😎")
st.page_link("pages/projects.py",label="My projects",icon="💼")
st.page_link("pages/achievements.py",label="Achievements",icon="🏆")
st.divider()
st.title("These are the Recommendation letters below")
st.link_button("Cybersecurity & Digital Forensics","https://docs.google.com/document/d/1PaYX0i1-vBfCUTf_upenT20NChQDB5nj/edit?usp=sharing&ouid=104159583048794347910&rtpof=true&sd=true")
st.link_button("Information Technology","https://docs.google.com/document/d/1PenPIkocIHWqWuSZoc0WKQHKJDJXGnZ2/edit?usp=sharing&ouid=104159583048794347910&rtpof=true&sd=true")
st.link_button("Computing with Law", "https://docs.google.com/document/d/1P_lwAi3vWpR7oyutGNJnFxixdEStPJld/edit?usp=sharing&ouid=104159583048794347910&rtpof=true&sd=true")
st.divider()
st.write("If you got any queries, contact me at lowliwen2409@gmail.com")
